#server:
#  port: 9999
#  servlet:
#    context-path: /note
spring:
#  messages:
#    basename: i18n.login
  thymeleaf:
    cache: false
  datasource:
    master:
          url: jdbc:mysql://11.11.11.100:3306/nova?useSSL=false
          username: opviewuser
          password: opview4/25
    # \u4F7F\u7528druid\u6570\u636E\u6E90
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
    cluster:
      - key: cinder
        password: opview4/25
        url: jdbc:mysql://11.11.11.100:3306/cinder?glanceuseSSL=false
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: opviewuser
        type: com.zaxxer.hikari.HikariDataSource
      - key: neutron
        password: opview4/25
        url: jdbc:mysql://11.11.11.100:3306/neutron?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: opviewuser

        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml